[build]
  functions = "functions" # Specify the directory where your Netlify functions are located

[[headers]]
  # Enable CORS for your Netlify functions
  for = "/*.netlify/functions/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"

[[redirects]]
  # Redirect form submissions to your Netlify function
  from = "/contact"
  to = "/.netlify/functions/sendEmail"
  status = 200
  force = true
